sudo: required

addons:
  chrome: stable

language: ruby

rvm: 2.5.0

cache: bundler

before_script:
 - chmod +x ./script/cibuild
 - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - /.*/     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


