---
layout: project
project_name: Flow-Assisted Batteries
project_headline: Energy storage for the future
project_desc: Renewable energy sources like wind and solar provide power output that depends largely on environmental conditions. Efficient, affordable energy storage systems are essential for the viability of renewable energy. Join us as we work on an ambitious, multi-disciplinary project in the design and construction of a sustainable microgrid system on campus using rechargeable redox flow batteries.
project_box: >
  The flow cell project began at UBC in 2016 as a research project, intended to research the viability of using a flow-assisted Zinc - Nickel oxide battery as a means of energy storage. Essentially, the flow cell is a rechargeable battery, with some different properties that make it an interesting research topic.Conventional rechargeable batteries use stationary (i.e. non-flowing) solutions, with environmentally harmful materials, such as those in lead-acid or lithium-ion batteries. These batteries are used for a certain number of charge-discharge cycles with a certain efficiency. When applying a flowing electrolytic solution to a normal battery, the energy efficiency of it is greatly increased, due to the electrodes' increased exposure to the ions in solution. This is the main benefit of using flow cells instead of conventional rechargeable batteries. In addition, the materials used in making conventional batteries are normally quite toxic or environmentally harmful. Our flow cell uses Zinc and Nickel oxide with KOH and ZnO solutions, which are all non-toxic, giving us another reason to look into the viability of these cells. Our goal in this project is to vary the parameters of the cell, such as cell geometry and electrolyte flow, in order to optimize cell performance. We will also be researching how to tackle the issue of dendritic growth (see "Technology" section below for details). Eventually, we would like to build a microgrid of flow batteries on campus.
---

# Technology

## Chemistry
As mentioned before, our flow cell uses Zinc and Nickel oxide, with a flowing solution of ZnO in aqueous KOH. This operates as a normal electrochemical cell, with the zinc dissolving and depositing onto a copper substrate. (Note: the reactions are summarized below) When charging, the electron surplus at the copper anode will cause the Zn(OH)42- ions to form solid Zn and 4 OH- groups. The Zn deposits are said to be dendritic, due to their growth pattern. Dendritic growth is random and very difficult to control, meaning that any unusual growth can touch something else in the cell and cause an internal short, which is a large obstacle for advancements in flow cell technology.
