#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --check_html --check_external_hash --check_opengraph --check_favicon --disable-external --url-ignore "/#.*/"